# Generated by Django 4.2.7 on 2025-09-02 10:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("workloads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MigrationTarget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The timestamp when the object was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The timestamp when the object was last updated.",
                    ),
                ),
                (
                    "cloud_type",
                    models.CharField(
                        choices=[
                            ("aws", "Amazon Web Services"),
                            ("azure", "Microsoft Azure"),
                            ("vsphere", "VMware vSphere"),
                            ("vcloud", "VMware vCloud"),
                        ],
                        help_text="The target cloud platform.",
                        max_length=10,
                    ),
                ),
                (
                    "cloud_credentials",
                    models.ForeignKey(
                        help_text="Credentials for accessing the target cloud environment.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="migration_targets",
                        to="workloads.credentials",
                    ),
                ),
                (
                    "target_vm",
                    models.OneToOneField(
                        help_text="The workload object representing the target virtual machine.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="migration_target_vm",
                        to="workloads.workload",
                    ),
                ),
            ],
            options={
                "verbose_name": "Migration Target",
                "verbose_name_plural": "Migration Targets",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Migration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The timestamp when the object was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The timestamp when the object was last updated.",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("running", "Running"),
                            ("error", "Error"),
                            ("success", "Success"),
                        ],
                        db_index=True,
                        default="not_started",
                        help_text="The current state of the migration process.",
                        max_length=20,
                    ),
                ),
                (
                    "selected_mount_points",
                    models.ManyToManyField(
                        help_text="The specific mount points selected for this migration.",
                        related_name="migrations",
                        to="workloads.mountpoint",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        help_text="The source workload to be migrated.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_migrations",
                        to="workloads.workload",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        help_text="The configured destination for the migration.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_migrations",
                        to="migration_manager.migrationtarget",
                    ),
                ),
            ],
            options={
                "verbose_name": "Migration",
                "verbose_name_plural": "Migrations",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
