version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: migration_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: migration_redis

  app:
    build: .
    container_name: migration_app
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/home/appuser/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  celery_worker:
    build: .
    container_name: migration_celery_worker
    command: celery -A config worker -l info
    volumes:
      - .:/home/appuser/app
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
